name: Deploy API Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'openapi/**'
      # složka openapi v rootu
      # == pipeline se spustí pokud nastane změna ve složce 'openapi' v branchi main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        # použité verze je třeba občas zaktualizovat 

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
         # použité verze je třeba občas zaktualizovat 
        with:
          node-version: '24'
          # verze nodeJS - GitHub vyžaduje použití min. verze

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Build HTML documentation
        run: |
            mkdir -p _site
            redocly build-docs openapi/*.yaml -o _site/index.html
        # HTMN soubor se vygeneruje ze souboru .yaml ve složce 'openapi'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
                 # použité verze je třeba občas zaktualizovat 
        with:
           path: '_site'   # ← nahraje pouze vygenerovaný HTML soubor

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
                 # použité verze je třeba občas zaktualizovat 
